Fix use of d_type field on SunOS
SunOS does not provide the d_type field in a directory entry.

The code now checks that d_type is available using
AC_STRUCT_DIRENT_D_TYPE and use it conditionnaly.

Fix compilation error on SunOS:
configfile.l: In function 'DBGetReaderListDir':
configfile.l:293:16: error: 'struct dirent' has no member named 'd_type'
    if (direntry->d_type == DT_UNKNOWN)
                ^
configfile.l:293:28: error: 'DT_UNKNOWN' undeclared (first use in this function)
    if (direntry->d_type == DT_UNKNOWN)
                            ^
configfile.l:293:28: note: each undeclared identifier is reported only once for each function it appears in
configfile.l:312:17: error: 'struct dirent' has no member named 'd_type'
     if (direntry->d_type != DT_REG)
                 ^
configfile.l:312:29: error: 'DT_REG' undeclared (first use in this function)
     if (direntry->d_type != DT_REG)
                             ^

Thanks to risto3 for the bug report
https://github.com/LudovicRousseau/PCSC/issues/6