Python 3: use PEP 3110 exception format
Use the "new" syntax "except Exception as message:" supported since
Python 2.6

  File "SCardCancel2.py", line 47
    except Exception, message:
                    ^
SyntaxError: invalid syntax