Use correct prototype for pcsc_stringify_error()
If NO_LOG is defined the code failed to build on Mac OS X:
error.c:53:16: error: conflicting types for 'pcsc_stringify_error'
PCSC_API char* pcsc_stringify_error(const long pcscError)
               ^
../src/PCSC/pcsclite.h:237:7: note: previous declaration is here
char *pcsc_stringify_error(const LONG);
      ^
1 error generated.

The prototype used in the case of NO_LOG was not the same as in the normal
case: "long" instead of "LONG".

Thanks to Frank Morgner for the bug report.
https://github.com/LudovicRousseau/PCSC/pull/1