readerfactory: fix compilation warning on SunOS
The code uses alloca() so we #include "alloca.h"

readerfactory.c: In function 'RFAddReader':
readerfactory.c:211:2: warning: implicit declaration of function 'alloca' [-Wimplicit-function-declaration]
  readerName = alloca(strlen(readerNameLong)+1);
  ^
readerfactory.c:211:15: warning: incompatible implicit declaration of built-in function 'alloca'
  readerName = alloca(strlen(readerNameLong)+1);
               ^