readerfactory.c: do not #include <alloca.h>
Compilation fails on NetBSD with:
../src/readerfactory.c:52:10: fatal error: alloca.h: No such file or directory
 #include <alloca.h>
          ^~~~~~~~~~

alloca(3) is defined in stdlib.h on NetBSD.